### PR TITLE
Reset agent state if the instance id changed on agent restart

### LINKED ISSUE #859: ECS agent doesn't reset task state when instance id is modified
Repro steps: 
1. Launch instance with Amazon Linux and ecsInstanceRole in default ECS cluster 
2. Install ecs-init package 
3. Start ecs, and let agent register 
4. Run a task
5. Stop ecs
6. Modify the ec2 instance id in the state file
7. Start ecs
8. Inspect the state file/introspection API to illustrate that task ID from previous instance id is persisted in the state file

### PR DESCRIPTION
**Pull request by richardpen**
### Summary

Fix #859 

### Implementation details

Rest the agent state when detected the instance id is different from the one stored in the agent state file.

### Testing

- [x] Builds on Linux (`make release`)
- [x] Builds on Windows (`go build -out amazon-ecs-agent.exe ./agent`)
- [x] Unit tests on Linux (`make test`) pass
- [x] Unit tests on Windows (`go test -timeout=25s ./agent/...`) pass
- [x] Integration tests on Linux (`make run-integ-tests`) pass
- [x] Integration tests on Windows (`.\scripts\run-integ-tests.ps1`) pass
- [x] Functional tests on Linux (`make run-functional-tests`) pass
- [x] Functional tests on Windows (`.\scripts\run-functional-tests.ps1`) pass
- [x] Manually tested
New tests cover the changes: 

### Licensing

This contribution is under the terms of the Apache 2.0 License: 
yes

### CODE REVIEW

File: agent/engine/dockerstate/docker_task_engine_state.go [hunk 1]
```diff
@@ -96,6 +98,18 @@ func newDockerTaskEngineState() *DockerTaskEngineState {
 	}
 }
 
+// Reset resets all the states
+func (state *DockerTaskEngineState) Reset() {
+	state.lock.RLock()
```
Comment (aaithal) [inline agent/engine/dockerstate/docker_task_engine_state.go]: This should be `Lock` and `Unlock` instead of `RLock` and `RUnlock`

File: agent/app/agent.go [hunk 2]
```diff
@@ -232,6 +232,8 @@ func (agent *ecsAgent) newTaskEngine(containerChangeEventStream *eventstream.Eve
 		log.Warnf(instanceIDMismatchErrorFormat,
 			previousEC2InstanceID, currentEC2InstanceID)
 
+		// Reset agent state as a new container instance
+		state.Reset()
```
Comment (aaithal) [inline agent/app/agent.go]: It seems like you'd need to invoke `statemanager.Save()` here as well? Otherwise, an agent restart here may still result in the wrong state, yes?

Comment (richardpen) [inline agent/app/agent.go]: I don't think so, the file will be override later. And if agent restart at this point, it will run into the same code path `state.Reset` will be executed again.

File: agent/engine/dockerstate/docker_task_engine_state.go [hunk 3]
```diff
@@ -96,6 +98,18 @@ func newDockerTaskEngineState() *DockerTaskEngineState {
 	}
 }
 
+// Reset resets all the states
+func (state *DockerTaskEngineState) Reset() {
```
Comment (aaithal) [inline agent/engine/dockerstate/docker_task_engine_state.go]: Can you modify this so that you extract all the `state.xxx=make()` bits into a new method, and invoke it here and from `newDockerTaskEngineState()` so that in future if we modify this struct to persist more state, there's no cognitive load of updating `Reset` method as well?
