### PR TITLE
volume: set the type to default if not specified

### LINKED ISSUE #1507: Agent 1.20.0 not starting after upgrade from 1.19.1
### Summary

Agent 1.20.0 not starting with saved state from 1.19.1

### Description

restarting docker doesn't help
removing all running containers and issuing a start ecs doesnt help
the only thing that works is to purge /var/lib/ecs/data/ecs_agent_data.json
and then 
start ecs
however this then registers as a new ecs container instance and loses previous container instance arn

### Expected Behavior
after upgrade expected ecs-agent to start

### Observed Behavior
after ecs-agent update from 1.19.1 to 1.20.0 
docker ecs-agent fails to start

### Supporting Log Snippets

1.19.1 shutdown
2018-08-07T20:36:07Z [INFO] Saving state! module="statemanager"
2018-08-07T20:37:42Z [INFO] Saving state! module="statemanager"
2018-08-07T20:37:43Z [INFO] Loading configuration
2018-08-07T20:37:43Z [INFO] Amazon ECS agent Version: 1.20.0, Commit: cd331230
2018-08-07T20:37:43Z [INFO] Creating root ecs cgroup: /ecs
2018-08-07T20:37:43Z [INFO] Creating cgroup /ecs
2018-08-07T20:37:43Z [INFO] Loading state! module="statemanager"
2018-08-07T20:37:43Z [INFO] Event stream ContainerChange start listening...
2018-08-07T20:37:43Z [CRITICAL] Error loading previously saved state: invalid Volume: must include a type

1.20.0 startup
>docker logs ecs-agent
2018-08-08T12:33:52Z [INFO] Loading configuration
2018-08-08T12:33:52Z [INFO] Amazon ECS agent Version: 1.20.0, Commit: cd331230
2018-08-08T12:33:52Z [INFO] Creating root ecs cgroup: /ecs
2018-08-08T12:33:52Z [INFO] Creating cgroup /ecs
2018-08-08T12:33:52Z [INFO] Loading state! module="statemanager"
2018-08-08T12:33:52Z [INFO] Event stream ContainerChange start listening...
2018-08-08T12:33:52Z [CRITICAL] Error loading previously saved state: invalid Volume: must include a type

after purging  /var/lib/ecs/data/ecs_agent_data.json

 docker logs ecs-agent
2018-08-08T13:30:49Z [INFO] Loading configuration
2018-08-08T13:30:49Z [INFO] Amazon ECS agent Version: 1.20.0, Commit: cd331230
2018-08-08T13:30:49Z [INFO] Creating root ecs cgroup: /ecs
2018-08-08T13:30:49Z [INFO] Creating cgroup /ecs
2018-08-08T13:30:49Z [INFO] Loading state! module="statemanager"
2018-08-08T13:30:49Z [INFO] Event stream ContainerChange start listening...
2018-08-08T13:30:49Z [INFO] Registering Instance with ECS
2018-08-08T13:30:49Z [INFO] Registered container instance with cluster!
2018-08-08T13:30:49Z [INFO] Registration completed successfully. I am running as '<NEW ARN>'
2018-08-08T13:30:49Z [INFO] Saving state! module="statemanager"
2018-08-08T13:30:49Z [INFO] Beginning Polling for updates
2018-08-08T13:30:49Z [INFO] Event stream DeregisterContainerInstance start listening...
2018-08-08T13:30:49Z [INFO] Initializing stats engine
2018-08-08T13:30:49Z [INFO] NO_PROXY set:169.254.169.254,169.254.170.2,/var/run/docker.sock
2018-08-08T13:30:49Z [INFO] Connected to TCS endpoint
2018-08-08T13:30:49Z [INFO] Connected to ACS endpoint

### PR DESCRIPTION
**Pull request by richardpen**
With the new volume driver support, a new field was added to the volume
struct, where it's not set in the old state file. This PR try to set the
volume type to default if it's not set or restored from old state file.

### Summary

Fix #1507 

### Testing

- [x] Builds on Linux (`make release`)
- [x] Builds on Windows (`go build -out amazon-ecs-agent.exe ./agent`)
- [x] Unit tests on Linux (`make test`) pass
- [x] Unit tests on Windows (`go test -timeout=25s ./agent/...`) pass
- [x] Integration tests on Linux (`make run-integ-tests`) pass
- [ ] Integration tests on Windows (`.\scripts\run-integ-tests.ps1`) pass
- [x] Functional tests on Linux (`make run-functional-tests`) pass
- [ ] Functional tests on Windows (`.\scripts\run-functional-tests.ps1`) pass

New tests cover the changes: 

### Licensing

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: agent/api/task/taskvolume.go [hunk 1]
```diff
@@ -73,6 +75,10 @@ func (tv *TaskVolume) UnmarshalJSON(b []byte) error {
 func (tv *TaskVolume) MarshalJSON() ([]byte, error) {
 	result := make(map[string]interface{})
 
+	if len(tv.Type) == 0 {
```
Comment (sharanyad) [inline agent/api/task/taskvolume.go]: Would we require this in Marshal? since the empty volume's MarshalJSON will now contain type as "host"?

Comment (yunhee-l) [reply agent/api/task/taskvolume.go]: If we have the check in unmarshalling, I don't think it's necessary in marshalling?

Comment (richardpen) [reply agent/api/task/taskvolume.go]: yes, I agree with that this probably isn't required as it's already handled in the Marshal, but adding here to keep the consistency. I can remove that if you feel strongly about that.

Comment (yunhee-l) [reply agent/api/task/taskvolume.go]: no I'm ok with double-checking.

File: agent/api/task/taskvolume.go [hunk 2]
```diff
@@ -51,7 +52,8 @@ func (tv *TaskVolume) UnmarshalJSON(b []byte) error {
 
 	volumeType, ok := intermediate["type"]
 	if !ok {
-		return errors.New("invalid Volume: must include a type")
+		volumeType = []byte(`"host"`)
+		seelog.Infof("Unmarshal task volume: volume type not specified, default to host")
```
Comment (sharanyad) [inline agent/api/task/taskvolume.go]: This can just be at the debug level.

File: agent/functional_tests/testdata/taskdefinitions/task-shared-vol-read/task-definition.json [hunk 3]
```diff
@@ -23,10 +23,6 @@
                 "scope": "shared",
                 "autoprovision": false,
                 "driver": "local",
-                "driverOpts": {
```
Comment (sharanyad) [inline agent/functional_tests/testdata/taskdefinitions/task-shared-vol-read/task-definition.json]: Why has this been removed?

File: agent/functional_tests/tests/functionaltests_unix_test.go [hunk 4]
```diff
@@ -910,16 +910,16 @@ func TestTwoTasksSharedLocalVolume(t *testing.T) {
 	wTask, err := agent.StartTask(t, "task-shared-vol-write")
 	require.NoError(t, err, "Register task definition failed")
 
-	// then reader task
-	rTask, err := agent.StartTask(t, "task-shared-vol-read")
-	require.NoError(t, err, "Register task definition failed")
-
-	// clean up
+	// Wait for the first task to create the volume
 	wErr := wTask.WaitStopped(waitTaskStateChangeDuration)
```
Comment (sharanyad) [inline agent/functional_tests/tests/functionaltests_unix_test.go]: Should we just wait until the first task transitions to `RUNNING` instead of `STOPPED`?

Comment (richardpen) [reply agent/functional_tests/tests/functionaltests_unix_test.go]: Yes, this just makes the change easier. Probably doing this in another PR.

File: agent/functional_tests/testdata/taskdefinitions/task-shared-vol-read/task-definition.json (hunk 3 above)
Comment (richardpen) [reply agent/functional_tests/testdata/taskdefinitions/task-shared-vol-read/task-definition.json]: I think `tmpfs` may not be a good option to test here, I saw wired things happen where the `write` happened but the file doesn't exist. I will need to investigate more about the option after this PR.

File: agent/api/task/taskvolume.go (hunk 2 above)
Comment (richardpen) [reply agent/api/task/taskvolume.go]: I think it should be `Info` level, as it's translating the task resource in a specific case.

File: agent/api/task/task.go [hunk 5]
```diff
@@ -552,6 +553,27 @@ func (task *Task) HostVolumeByName(name string) (taskresourcevolume.Volume, bool
...
+// volume feature.
+func (task *Task) UpdateMountPoints(cont *apicontainer.Container, vols map[string]string) {
+	for _, mountPoint := range cont.MountPoints {
+		containerPath := getCanonicalPath(mountPoint.ContainerPath)
+		hostPath, ok := vols[containerPath]
+		if !ok {
+			// /path/ -> /path or \path\ -> \path
+			hostPath, ok = vols[strings.TrimRight(containerPath, string(filepath.Separator))]
+		}
+		if ok {
```
[the remark this answers is not in the document]
Comment (sharanyad) [reply agent/api/task/task.go]: I didn't realize there was no `continue` inside the previous condition. We could refactor this later.
