### PR TITLE
Fix windows eventlog log format

### LINKED ISSUE #2346: Windows: Agent 1.36.1 does not write to windows logfile
### Summary

Agent 1.36.1 does not create or write to the windows logfile, which is usually located at `C:\ProgramData\Amazon\ECS\log\ecs-agent.log`

### Expected Behavior

Logfile should be written to

### Observed Behavior

It is not written to

### Details:

This is related to the rollback/bugfix that was made in release 1.36.1: https://github.com/aws/amazon-ecs-agent/commit/047b5c0041170883137de5d52b2bbfa4bcf638dc

Part of this revert commit should have been omitted, specifically the part that modifies the seelog list of "formats" (see https://github.com/aws/amazon-ecs-agent/commit/047b5c0041170883137de5d52b2bbfa4bcf638dc#diff-79427eb7cee91e1df7e0ac19caec58e0L115)

### PR DESCRIPTION
**Pull request by sparrc**
closes #2346

This line: `<format id="windows" format="%Msg" />` was mistakenly removed in an intermediary commit during work on our logging changes. It was then re-added but the commit that added it back in was reverted to fix an unrelated bug (see https://github.com/aws/amazon-ecs-agent/pull/2337)

This change adds this line back into our seelog config and adds windows unit tests to prevent this happening in the future.

### Licensing

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: agent/logger/log_windows_test.go [hunk 1]
```diff
@@ -0,0 +1,258 @@
+// +build windows
+
+// Copyright 2014-2015 Amazon.com, Inc. or its affiliates. All Rights Reserved.
```
Comment (fenxiong) [inline agent/logger/log_windows_test.go]: nit: 2014-2020
