### PR TITLE
Fix taskresource synchronize on agent restart

### LINKED ISSUE #1413: Initialize the member in resource during unmarshal
### Summary

When the agent restart, the resource struct is recovered from the state file, but the object inside the struct isn't initialized, so it will panic if you try to use it.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x92d3af]

goroutine 229 [running]:
github.com/aws/amazon-ecs-agent/agent/taskresource/cgroup.(*CgroupResource).Cleanup(0xc420229600, 0xc4202ff740, 0x2)
	/go/src/github.com/aws/amazon-ecs-agent/agent/taskresource/cgroup/cgroup.go:273 +0x3f
github.com/aws/amazon-ecs-agent/agent/engine.(*DockerTaskEngine).deleteTask(0xc4202d78c0, 0xc420358000)
	/go/src/github.com/aws/amazon-ecs-agent/agent/engine/docker_task_engine.go:458 +0x9e
github.com/aws/amazon-ecs-agent/agent/engine.(*managedTask).cleanupTask(0xc420185ee0, 0xdf8475800)
	/go/src/github.com/aws/amazon-ecs-agent/agent/engine/task_manager.go:1074 +0x29f
github.com/aws/amazon-ecs-agent/agent/engine.(*managedTask).overseeTask(0xc420185ee0)
	/go/src/github.com/aws/amazon-ecs-agent/agent/engine/task_manager.go:246 +0x2ed
created by github.com/aws/amazon-ecs-agent/agent/engine.(*DockerTaskEngine).startTask
	/go/src/github.com/aws/amazon-ecs-agent/agent/engine/docker_task_engine.go:507 +0x9c
```

### PR DESCRIPTION
**Pull request by richardpen**
### Summary

Fix #1413 
### Testing

- [x] Builds on Linux (`make release`)
- [x] Builds on Windows (`go build -out amazon-ecs-agent.exe ./agent`)
- [x] Unit tests on Linux (`make test`) pass
- [x] Unit tests on Windows (`go test -timeout=25s ./agent/...`) pass
- [x] Integration tests on Linux (`make run-integ-tests`) pass
- [x] Integration tests on Windows (`.\scripts\run-integ-tests.ps1`) pass
- [x] Functional tests on Linux (`make run-functional-tests`) pass
- [x] Functional tests on Windows (`.\scripts\run-functional-tests.ps1`) pass

New tests cover the changes: 

### Licensing

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: agent/taskresource/cgroup/cgroup.go [hunk 1]
```diff
@@ -345,3 +348,13 @@ func (cgroup *CgroupResource) GetCgroupMountPath() string {
 	defer cgroup.lock.RUnlock()
 	return cgroup.cgroupMountPath
 }
+
+// Synchronize fills the resource fileds
+func (cgroup *CgroupResource) Synchronize(resourceFields *taskresource.ResourceFields) {
```
Comment (aaithal) [inline agent/taskresource/cgroup/cgroup.go]: This is just doing initialization. Can you rename `Synchronize` to `Initialize` everywhere?

File: agent/taskresource/cgroup/cgroup.go [hunk 2]
```diff
@@ -284,11 +284,12 @@ func (cgroup *CgroupResource) Cleanup() error {
...
 // cgroupResourceJSON duplicates CgroupResource fields, only for marshalling and unmarshalling purposes
 type cgroupResourceJSON struct {
-	CgroupRoot      string        `json:"CgroupRoot"`
-	CgroupMountPath string        `json:"CgroupMountPath"`
-	CreatedAt       time.Time     `json:",omitempty"`
-	DesiredStatus   *CgroupStatus `json:"DesiredStatus"`
-	KnownStatus     *CgroupStatus `json:"KnownStatus"`
+	CgroupRoot      string               `json:"CgroupRoot"`
+	CgroupMountPath string               `json:"CgroupMountPath"`
+	CreatedAt       time.Time            `json:",omitempty"`
```
Comment (aaithal) [inline agent/taskresource/cgroup/cgroup.go]: Can you add the `CreatedAt` json label as well?

File: agent/taskresource/cgroup/cgroup.go [hunk 3]
```diff
@@ -284,11 +284,12 @@ func (cgroup *CgroupResource) Cleanup() error {
 
 // cgroupResourceJSON duplicates CgroupResource fields, only for marshalling and unmarshalling purposes
 type cgroupResourceJSON struct {
-	CgroupRoot      string        `json:"CgroupRoot"`
-	CgroupMountPath string        `json:"CgroupMountPath"`
-	CreatedAt       time.Time     `json:",omitempty"`
-	DesiredStatus   *CgroupStatus `json:"DesiredStatus"`
-	KnownStatus     *CgroupStatus `json:"KnownStatus"`
+	CgroupRoot      string               `json:"CgroupRoot"`
```
Comment (aaithal) [inline agent/taskresource/cgroup/cgroup.go]: There's a discrepancy wrt JSON labels between this and https://github.com/aws/amazon-ecs-agent/pull/1406/files#diff-321265a19fa4fe3d5d21afce0e0c481dR289. There, labels begin with lower case letters. Here, they begin with upper letters. We should stick with one format.

File: agent/api/task/task.go [hunk 4]
```diff
@@ -1213,3 +1213,17 @@ func (task *Task) AddResource(resourceType string, resource taskresource.TaskRes
 	defer task.lock.Unlock()
 	task.ResourcesMapUnsafe[resourceType] = append(task.ResourcesMapUnsafe[resourceType], resource)
 }
+
+// Synchronize initializes the required field in the task on agent restart
+// Some of the fields in task isn't saved in the agent state file, agent needs
+// to initialize these fields before processing the task, eg: docker client in resource
+func (task *Task) Synchronize(resourceFields *taskresource.ResourceFields) {
```
Comment (petderek) [inline agent/api/task/task.go]: `InitializeAll` maybe?

File: agent/api/task/task.go [hunk 5]
```diff
@@ -1213,3 +1213,17 @@ func (task *Task) AddResource(resourceType string, resource taskresource.TaskRes
...
+	task.lock.Lock()
+	defer task.lock.Unlock()
+
+	for _, resources := range task.ResourcesMapUnsafe {
+		for _, resource := range resources {
+			resource.Initialize(resourceFields)
```
Comment (petderek) [inline agent/api/task/task.go]: Is this going to be safe to reapply?

Should we make it clear that _all_ resources need to behave this way?

File: agent/taskresource/cgroup/cgroup.go [hunk 6]
```diff
@@ -345,3 +348,13 @@ func (cgroup *CgroupResource) GetCgroupMountPath() string {
...
 	return cgroup.cgroupMountPath
 }
+
+// Initialize initializes the resource fileds in cgroup
+func (cgroup *CgroupResource) Initialize(resourceFields *taskresource.ResourceFields) {
+	cgroup.lock.Lock()
+	defer cgroup.lock.Unlock()
+
+	cgroup.initializeResourceStatusToTransitionFunction()
+	cgroup.ioutil = resourceFields.IOUtil
```
Comment (petderek) [inline agent/taskresource/cgroup/cgroup.go]: wait -- is the ioutil mock the only issue causing the panic?

File: agent/engine/docker_task_engine_test.go [hunk 7]
```diff
@@ -275,7 +277,7 @@ func TestTaskWithSteadyStateResourcesProvisioned(t *testing.T) {
 	sleepTask := testdata.LoadTask("sleep5")
 	sleepContainer := sleepTask.Containers[0]
 	sleepContainer.TransitionDependenciesMap = make(map[apicontainer.ContainerStatus]apicontainer.TransitionDependencySet)
-	sleepContainer.BuildContainerDependency("pause", apicontainer.ContainerRunning, apicontainer.ContainerPulled)
+	sleepContainer.BuildContainerDependency("pause", apicontainer.ContainerResourcesProvisioned, apicontainer.ContainerPulled)
```
Comment (fenxiong) [inline agent/engine/docker_task_engine_test.go]: Should the desire status set in line 288 also set to ContainerReousrcesProvisioned?

File: agent/taskresource/cgroup/cgroup.go (hunk 6 above)
Comment (richardpen) [reply agent/taskresource/cgroup/cgroup.go]: No, the error is coming from agent runtime, not the test. Because the ioutil is nil, when agent try to call the ioutil.remove, it panics.

File: agent/api/task/task.go (hunk 5 above)
Comment (richardpen) [reply agent/api/task/task.go]: yes, it's ok to reapply as it doesn't change any state. 
>Should we make it clear that all resources need to behave this way?

I think this depends on whether the resource needs to be initialized on restart.
