### PR TITLE
Fix container change not reported when task status is NONE

### LINKED ISSUE #1075: "Network Bindings - not configured" although there are port mappings in the container.
This is a duplicate of #1057, #1063, and possibly #1064. #1063 was closed as fixed in version 1.15.1, however, I had a chance to test today and the problem is still present in that version.

### PR DESCRIPTION
**Pull request by richardpen**
### Summary

Fix #1075 

### Implementation details

Task status with NONE is dropped in taskShouldBeSent, this commit makes the taskShouldBeSent more clear and stronger to handle both container  event and task event.

### Testing

- [x] Builds on Linux (`make release`)
- [x] Builds on Windows (`go build -out amazon-ecs-agent.exe ./agent`)
- [x] Unit tests on Linux (`make test`) pass
- [x] Unit tests on Windows (`go test -timeout=25s ./agent/...`) pass
- [x] Integration tests on Linux (`make run-integ-tests`) pass
- [x] Integration tests on Windows (`.\scripts\run-integ-tests.ps1`) pass
- [x] Functional tests on Linux (`make run-functional-tests`) pass
- [x] Functional tests on Windows (`.\scripts\run-functional-tests.ps1`) pass
- [x] Manual test.

New tests cover the changes: 
yes
### Licensing

This contribution is under the terms of the Apache 2.0 License: 
yes

### CODE REVIEW

**Comment by nmeyerhans** [comment]
I've tested this with my repro case for #1075 and it passes. Task shows `lastStatus: PENDING` while some containers are RUNNING and others are PENDING and blocked on image pulls. Containers within the task that are RUNNING have fully populated metadata, while PENDING containers have empty metadata. As containers start, the task object returned by DescribeTasks is populated, such that when the task itself finally transitions to RUNNING all of the containers are fully described. This matches the desired behavior, so from the outside this looks good.

File: agent/api/ecsclient/client.go [hunk 1]
```diff
@@ -312,12 +312,6 @@ func (client *APIECSClient) SubmitTaskStateChange(change api.TaskStateChange) er
 		return nil
 	}
 
-	// Submit task state change
-	if change.Status == api.TaskStatusNone {
-		seelog.Warnf("SubmitTaskStateChange called with an invalid change: %s", change.String())
-		return errors.New("ecs api client: SubmitTaskStateChange called with an invalid change")
-	}
-
 	if change.Status != api.TaskRunning && change.Status != api.TaskStopped && len(change.Containers) == 0 {
```
Comment (aaithal) [inline agent/api/ecsclient/client.go]: let's also get rid of this block altogether. This determination should be happening in `sendableEvent .taskShouldBeSent` method: https://github.com/richardpen/amazon-ecs-agent/blob/fix-1075/agent/eventhandler/task_handler_types.go#L67
